{% set name = "pytest-harvest" %}
{% set version = "1.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27cfa4cf1f2e43d1e7749c282e0fe72d30e90e89bede6b30a59b626848c7d418

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - decopatch >=1.4.8
    - makefun >=1.5
    - pytest >=2
    - six

test:
  imports:
    - pytest_harvest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smarie/python-pytest-harvest
  summary: Store data created during your pytest tests execution
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Store data created during your `pytest` tests execution, and
    retrieve it at the end of the session, e.g. for applicative
    benchmarking purposes.
  doc_url: https://smarie.github.io/python-pytest-harvest/
  dev_url: https://github.com/smarie/python-pytest-harvest

extra:
  recipe-maintainers:
    - harelwa
